<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class JobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jobs = [
            // ACME Tech (Company 1)
            ['company_id' => 1, 'category_id' => 1, 'title' => 'Senior PHP Developer', 'description' => 'We seek an experienced PHP developer to lead our backend infrastructure. 5+ years experience required.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'senior', 'salary_min' => 150000, 'salary_max' => 200000, 'requirements' => 'PHP 8+, Laravel, MySQL', 'benefits' => 'Health Insurance, Gym Membership', 'status' => 'published', 'published_at' => now()],
            ['company_id' => 1, 'category_id' => 1, 'title' => 'React Frontend Developer', 'description' => 'Join our frontend team building modern web applications.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 100000, 'salary_max' => 150000, 'requirements' => 'React, JavaScript, CSS', 'benefits' => 'Remote Work, Training Allowance', 'status' => 'published', 'published_at' => now()],
            ['company_id' => 1, 'category_id' => 1, 'title' => 'DevOps Engineer', 'description' => 'Manage cloud infrastructure and deployment pipelines.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 120000, 'salary_max' => 160000, 'requirements' => 'Docker, Kubernetes, AWS', 'benefits' => 'Tech Allowance, Career Development', 'status' => 'published', 'published_at' => now()->subDays(1)],
            ['company_id' => 1, 'category_id' => 1, 'title' => 'QA Automation Specialist', 'description' => 'Develop and maintain automated testing suites.', 'location' => 'Quezon City', 'job_type' => 'full-time', 'experience_level' => 'entry', 'salary_min' => 50000, 'salary_max' => 80000, 'requirements' => 'Selenium, TestNG, Java', 'benefits' => 'Training, Health Benefits', 'status' => 'published', 'published_at' => now()->subDays(3)],

            // Global Finance (Company 2)
            ['company_id' => 2, 'category_id' => 3, 'title' => 'Financial Analyst', 'description' => 'Analyze market trends and provide investment recommendations.', 'location' => 'Makati', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 90000, 'salary_max' => 130000, 'requirements' => 'Finance Degree, Excel, Bloomberg', 'benefits' => 'Bonus, Insurance, HMO', 'status' => 'published', 'published_at' => now()],
            ['company_id' => 2, 'category_id' => 3, 'title' => 'Accountant', 'description' => 'Manage financial records and ensure compliance.', 'location' => 'Makati', 'job_type' => 'full-time', 'experience_level' => 'entry', 'salary_min' => 40000, 'salary_max' => 60000, 'requirements' => 'CPA, Accounting Software', 'benefits' => 'Health Insurance, Allowances', 'status' => 'published', 'published_at' => now()->subDays(2)],
            ['company_id' => 2, 'category_id' => 5, 'title' => 'HR Manager', 'description' => 'Oversee recruitment, training, and employee relations.', 'location' => 'Makati', 'job_type' => 'full-time', 'experience_level' => 'senior', 'salary_min' => 110000, 'salary_max' => 160000, 'requirements' => 'HR Degree, 5+ years experience', 'benefits' => 'Car Allowance, Conference Attendance', 'status' => 'published', 'published_at' => now()->subDays(5)],

            // PhilHealth (Company 3)
            ['company_id' => 3, 'category_id' => 2, 'title' => 'Registered Nurse', 'description' => 'Provide patient care in our modern healthcare facility.', 'location' => 'Quezon City', 'job_type' => 'full-time', 'experience_level' => 'entry', 'salary_min' => 35000, 'salary_max' => 55000, 'requirements' => 'Nursing License, RN certification', 'benefits' => 'Hazard Pay, Meal Allowance', 'status' => 'published', 'published_at' => now()],
            ['company_id' => 3, 'category_id' => 2, 'title' => 'Medical Doctor', 'description' => 'Join our team of healthcare professionals.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 150000, 'salary_max' => 200000, 'requirements' => 'MD, PRC license', 'benefits' => 'Clinic, Research Opportunity', 'status' => 'published', 'published_at' => now()->subDays(1)],
            ['company_id' => 3, 'category_id' => 2, 'title' => 'Medical Technologist', 'description' => 'Conduct medical tests and analysis.', 'location' => 'Quezon City', 'job_type' => 'full-time', 'experience_level' => 'entry', 'salary_min' => 30000, 'salary_max' => 45000, 'requirements' => 'Medical Technology License', 'benefits' => 'Health Insurance, Uniforms', 'status' => 'published', 'published_at' => now()->subDays(4)],

            // RetailCo (Company 4)
            ['company_id' => 4, 'category_id' => 10, 'title' => 'Store Manager', 'description' => 'Manage daily operations of our Cebu flagship store.', 'location' => 'Cebu', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 60000, 'salary_max' => 90000, 'requirements' => '3+ years retail management', 'benefits' => 'Employee Discount, Bonus', 'status' => 'published', 'published_at' => now()],
            ['company_id' => 4, 'category_id' => 10, 'title' => 'Sales Associate', 'description' => 'Customer service and sales in our retail stores.', 'location' => 'Cebu', 'job_type' => 'part-time', 'experience_level' => 'entry', 'salary_min' => 15000, 'salary_max' => 25000, 'requirements' => 'Customer service skills', 'benefits' => 'Staff Discount, Commissions', 'status' => 'published', 'published_at' => now()->subDays(2)],
            ['company_id' => 4, 'category_id' => 4, 'title' => 'Marketing Executive', 'description' => 'Develop and execute marketing campaigns.', 'location' => 'Cebu', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 70000, 'salary_max' => 100000, 'requirements' => 'Marketing Degree, Social Media', 'benefits' => 'Budget for campaigns, Training', 'status' => 'published', 'published_at' => now()->subDays(1)],

            // ConstructionPro (Company 5)
            ['company_id' => 5, 'category_id' => 6, 'title' => 'Civil Engineer', 'description' => 'Design and oversee infrastructure projects.', 'location' => 'Davao', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 85000, 'salary_max' => 120000, 'requirements' => 'CE License, CAD knowledge', 'benefits' => 'Site Allowance, Safety Equipment', 'status' => 'published', 'published_at' => now()],
            ['company_id' => 5, 'category_id' => 6, 'title' => 'Project Manager', 'description' => 'Manage construction projects from planning to completion.', 'location' => 'Davao', 'job_type' => 'full-time', 'experience_level' => 'senior', 'salary_min' => 120000, 'salary_max' => 160000, 'requirements' => '5+ years project management', 'benefits' => 'Car Allowance, Mobile Allowance', 'status' => 'published', 'published_at' => now()->subDays(3)],
            ['company_id' => 5, 'category_id' => 6, 'title' => 'Safety Officer', 'description' => 'Ensure workplace safety and compliance.', 'location' => 'Davao', 'job_type' => 'full-time', 'experience_level' => 'entry', 'salary_min' => 35000, 'salary_max' => 50000, 'requirements' => 'Safety certification', 'benefits' => 'Training, Gear Allowance', 'status' => 'published', 'published_at' => now()->subDays(6)],

            // StartupHub (Company 6)
            ['company_id' => 6, 'category_id' => 1, 'title' => 'Full Stack Developer', 'description' => 'Build web applications for startup clients. Fast-paced environment.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 95000, 'salary_max' => 135000, 'requirements' => 'Node.js, React, PostgreSQL', 'benefits' => 'Flexible hours, Stock options', 'status' => 'published', 'published_at' => now()],
            ['company_id' => 6, 'category_id' => 1, 'title' => 'Junior Developer', 'description' => 'Entry-level position for fresh graduates.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'entry', 'salary_min' => 40000, 'salary_max' => 60000, 'requirements' => 'JavaScript basics, willingness to learn', 'benefits' => 'Mentorship, Training Budget', 'status' => 'published', 'published_at' => now()->subDays(1)],
            ['company_id' => 6, 'category_id' => 1, 'title' => 'UI/UX Designer', 'description' => 'Design user interfaces for web and mobile apps.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 70000, 'salary_max' => 100000, 'requirements' => 'Figma, Adobe XD, Design principles', 'benefits' => 'Design tools, Portfolio building', 'status' => 'published', 'published_at' => now()->subDays(2)],

            // Infotech Innovations (Company 7)
            ['company_id' => 7, 'category_id' => 1, 'title' => 'Business Analyst', 'description' => 'Analyze business requirements and design IT solutions.', 'location' => 'Makati', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 85000, 'salary_max' => 125000, 'requirements' => 'Business Analysis, SQL, Agile', 'benefits' => 'Professional Development, Bonuses', 'status' => 'published', 'published_at' => now()],
            ['company_id' => 7, 'category_id' => 1, 'title' => 'Systems Administrator', 'description' => 'Maintain and manage IT infrastructure.', 'location' => 'Makati', 'job_type' => 'full-time', 'experience_level' => 'entry', 'salary_min' => 45000, 'salary_max' => 70000, 'requirements' => 'Windows/Linux administration', 'benefits' => 'On-call allowance, Training', 'status' => 'published', 'published_at' => now()->subDays(5)],

            // MediCare Services (Company 8)
            ['company_id' => 8, 'category_id' => 2, 'title' => 'Healthcare Administrator', 'description' => 'Manage hospital operations and patient services.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 65000, 'salary_max' => 95000, 'requirements' => 'Healthcare management experience', 'benefits' => 'Health benefits, HMO', 'status' => 'published', 'published_at' => now()],
            ['company_id' => 8, 'category_id' => 2, 'title' => 'Pharmacist', 'description' => 'Dispense medications and provide pharmacy services.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'entry', 'salary_min' => 40000, 'salary_max' => 65000, 'requirements' => 'Pharmacy License, RPh certification', 'benefits' => 'Shift allowance, Insurance', 'status' => 'published', 'published_at' => now()->subDays(1)],

            // EduPlus Learning (Company 9)
            ['company_id' => 9, 'category_id' => 7, 'title' => 'Subject Matter Expert', 'description' => 'Create educational content and course materials.', 'location' => 'Pasig', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 55000, 'salary_max' => 85000, 'requirements' => 'Degree in your field, Teaching experience', 'benefits' => 'Flexible hours, Learning materials', 'status' => 'published', 'published_at' => now()],
            ['company_id' => 9, 'category_id' => 7, 'title' => 'Curriculum Developer', 'description' => 'Design and develop educational programs.', 'location' => 'Pasig', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 60000, 'salary_max' => 90000, 'requirements' => 'Education background, Instructional design', 'benefits' => 'Professional development, Flexible schedule', 'status' => 'published', 'published_at' => now()->subDays(3)],

            // Logistics Express (Company 10)
            ['company_id' => 10, 'category_id' => 9, 'title' => 'Warehouse Supervisor', 'description' => 'Supervise warehouse operations and staff.', 'location' => 'Port Area', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 55000, 'salary_max' => 80000, 'requirements' => 'Warehouse management, Leadership', 'benefits' => 'Shift allowance, HMO', 'status' => 'published', 'published_at' => now()],
            ['company_id' => 10, 'category_id' => 9, 'title' => 'Logistics Coordinator', 'description' => 'Coordinate shipments and manage logistics.', 'location' => 'Port Area', 'job_type' => 'full-time', 'experience_level' => 'entry', 'salary_min' => 30000, 'salary_max' => 50000, 'requirements' => 'Logistics knowledge, Communication skills', 'benefits' => 'Transportation allowance, Bonuses', 'status' => 'published', 'published_at' => now()->subDays(2)],

            // Additional positions across companies for 50 total
            ['company_id' => 1, 'category_id' => 1, 'title' => 'Database Administrator', 'description' => 'Manage and optimize company databases.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 100000, 'salary_max' => 140000, 'requirements' => 'MySQL, PostgreSQL, backup management', 'benefits' => 'On-call pay, Training allowance', 'status' => 'published', 'published_at' => now()->subDays(1)],
            ['company_id' => 2, 'category_id' => 3, 'title' => 'Compliance Officer', 'description' => 'Ensure financial compliance and regulations.', 'location' => 'Makati', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 80000, 'salary_max' => 120000, 'requirements' => 'Compliance knowledge, Regulatory experience', 'benefits' => 'Bonuses, Professional development', 'status' => 'published', 'published_at' => now()->subDays(2)],
            ['company_id' => 3, 'category_id' => 2, 'title' => 'Hospital Admission Officer', 'description' => 'Handle patient admissions and records.', 'location' => 'Quezon City', 'job_type' => 'full-time', 'experience_level' => 'entry', 'salary_min' => 25000, 'salary_max' => 40000, 'requirements' => 'Customer service, Computer literacy', 'benefits' => 'Health benefits, Meal allowance', 'status' => 'published', 'published_at' => now()->subDays(3)],
            ['company_id' => 4, 'category_id' => 10, 'title' => 'Cashier', 'description' => 'Handle customer transactions and payments.', 'location' => 'Cebu', 'job_type' => 'part-time', 'experience_level' => 'entry', 'salary_min' => 14000, 'salary_max' => 22000, 'requirements' => 'Basic math, Customer service', 'benefits' => 'Staff discount, Flexible schedule', 'status' => 'published', 'published_at' => now()->subDays(1)],
            ['company_id' => 5, 'category_id' => 6, 'title' => 'Structural Engineer', 'description' => 'Design structural systems for buildings.', 'location' => 'Davao', 'job_type' => 'full-time', 'experience_level' => 'senior', 'salary_min' => 130000, 'salary_max' => 180000, 'requirements' => 'Structural engineering degree, 7+ years', 'benefits' => 'Car allowance, Performance bonus', 'status' => 'published', 'published_at' => now()->subDays(4)],
            ['company_id' => 6, 'category_id' => 1, 'title' => 'Backend Engineer', 'description' => 'Build scalable backend systems.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 100000, 'salary_max' => 150000, 'requirements' => 'Python, Django, REST API', 'benefits' => 'Stock options, Remote work', 'status' => 'published', 'published_at' => now()->subDays(2)],
            ['company_id' => 7, 'category_id' => 1, 'title' => 'IT Security Specialist', 'description' => 'Protect company IT infrastructure and data.', 'location' => 'Makati', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 95000, 'salary_max' => 140000, 'requirements' => 'Security certifications, Network knowledge', 'benefits' => 'Training budget, Performance bonuses', 'status' => 'published', 'published_at' => now()->subDays(1)],
            ['company_id' => 8, 'category_id' => 2, 'title' => 'Dental Assistant', 'description' => 'Assist dentists in patient care.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'entry', 'salary_min' => 25000, 'salary_max' => 40000, 'requirements' => 'Dental assistant certificate, Customer service', 'benefits' => 'Health benefits, Uniform provided', 'status' => 'published', 'published_at' => now()->subDays(2)],
            ['company_id' => 9, 'category_id' => 7, 'title' => 'Training Specialist', 'description' => 'Develop and deliver employee training programs.', 'location' => 'Pasig', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 50000, 'salary_max' => 80000, 'requirements' => 'Training experience, Communication skills', 'benefits' => 'Flexible hours, Professional development', 'status' => 'published', 'published_at' => now()->subDays(3)],
            ['company_id' => 10, 'category_id' => 9, 'title' => 'Delivery Driver', 'description' => 'Deliver packages to customers.', 'location' => 'Port Area', 'job_type' => 'full-time', 'experience_level' => 'entry', 'salary_min' => 28000, 'salary_max' => 45000, 'requirements' => 'Valid drivers license, Good driving record', 'benefits' => 'Fuel allowance, Bonus incentives', 'status' => 'published', 'published_at' => now()->subDays(1)],
            ['company_id' => 1, 'category_id' => 1, 'title' => 'Tech Lead', 'description' => 'Lead technical team and architecture decisions.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'senior', 'salary_min' => 170000, 'salary_max' => 220000, 'requirements' => 'Leadership, Architecture design, 8+ years', 'benefits' => 'Flexible work, Executive benefits', 'status' => 'published', 'published_at' => now()->subDays(5)],
            ['company_id' => 2, 'category_id' => 4, 'title' => 'Corporate Trainer', 'description' => 'Train employees on financial products.', 'location' => 'Makati', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 60000, 'salary_max' => 90000, 'requirements' => 'Training experience, Finance knowledge', 'benefits' => 'Training budget, Conference attendance', 'status' => 'published', 'published_at' => now()->subDays(2)],
            ['company_id' => 3, 'category_id' => 2, 'title' => 'Senior Nurse Manager', 'description' => 'Manage nursing staff and patient care quality.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'senior', 'salary_min' => 90000, 'salary_max' => 130000, 'requirements' => 'RN license, 7+ years nursing, Management', 'benefits' => 'Management allowance, HMO', 'status' => 'published', 'published_at' => now()->subDays(3)],
            ['company_id' => 4, 'category_id' => 4, 'title' => 'Digital Marketing Manager', 'description' => 'Manage digital marketing campaigns and strategies.', 'location' => 'Cebu', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 75000, 'salary_max' => 110000, 'requirements' => 'Digital marketing experience, Analytics', 'benefits' => 'Marketing budget, Flexible schedule', 'status' => 'published', 'published_at' => now()->subDays(1)],
            ['company_id' => 5, 'category_id' => 6, 'title' => 'Quantity Surveyor', 'description' => 'Manage project costs and budgets.', 'location' => 'Davao', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 80000, 'salary_max' => 115000, 'requirements' => 'QS diploma, Cost estimation experience', 'benefits' => 'Site allowance, Performance bonus', 'status' => 'published', 'published_at' => now()->subDays(2)],
            ['company_id' => 6, 'category_id' => 1, 'title' => 'Product Manager', 'description' => 'Manage product roadmap and features.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 110000, 'salary_max' => 160000, 'requirements' => 'Product management experience, Analytics', 'benefits' => 'Stock options, Conference budget', 'status' => 'published', 'published_at' => now()->subDays(4)],
            ['company_id' => 7, 'category_id' => 1, 'title' => 'Network Engineer', 'description' => 'Design and manage network infrastructure.', 'location' => 'Makati', 'job_type' => 'full-time', 'experience_level' => 'mid', 'salary_min' => 90000, 'salary_max' => 130000, 'requirements' => 'Networking certifications, Cisco knowledge', 'benefits' => 'On-call allowance, Training programs', 'status' => 'published', 'published_at' => now()->subDays(2)],
            ['company_id' => 8, 'category_id' => 2, 'title' => 'Lab Technician', 'description' => 'Conduct laboratory tests and analysis.', 'location' => 'Manila', 'job_type' => 'full-time', 'experience_level' => 'entry', 'salary_min' => 28000, 'salary_max' => 42000, 'requirements' => 'Lab skills, Safety awareness', 'benefits' => 'Health benefits, Safety equipment', 'status' => 'published', 'published_at' => now()->subDays(3)],
        ];

        foreach ($jobs as $job) {
            \App\Models\Job::create($job);
        }
    }
}
